# Generated by Django 5.0.6 on 2024-05-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityhub', '0002_user_address_user_birth_date_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('family_relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Cousin', 'Cousin'), ('Brother-in-law', 'Brother-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Paternal Grandfather', 'Paternal Grandfather'), ('Paternal Grandmother', 'Paternal Grandmother'), ('Maternal Grandfather', 'Maternal Grandfather'), ('Maternal Grandmother', 'Maternal Grandmother'), ('Paternal Uncle', 'Paternal Uncle'), ('Maternal Uncle', 'Maternal Uncle'), ('Paternal Aunt', 'Paternal Aunt'), ('Maternal Aunt', 'Maternal Aunt'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Grandson', 'Grandson'), ('Granddaughter', 'Granddaughter'), ('Father-in-law', 'Father-in-law'), ('Mother-in-law', 'Mother-in-law'), ('Son-in-law', 'Son-in-law'), ('Daughter-in-law', 'Daughter-in-law')], default='Father', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
