# Generated by Django 5.0.6 on 2024-05-27 17:03

import communityhub.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityhub', '0004_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/evnet', validators=[communityhub.validators.validate_file_size])),
                ('event_type', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Public', max_length=7)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='communityhub.group')),
            ],
        ),
    ]
