# Generated by Django 5.0.6 on 2024-05-27 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityhub', '0005_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('L', 'Leader'), ('M', 'Member')], default='M', max_length=1)),
                ('group', models.ManyToManyField(related_name='group_participant', to='communityhub.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
