# Generated by Django 5.0.6 on 2024-06-02 15:14

import communityhub.validators
import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityhub', '0008_event_created_at_event_event_date_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/event', validators=[communityhub.validators.validate_file_size]),
        ),
    ]
