# Generated by Django 5.0.6 on 2024-06-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityhub', '0009_event_location_event_place_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
    ]
